### ISSUE TITLE
Phone number that text is sent from has changed

### ISSUE THREAD

**Issue by ARCCCenter** [PacoVu/ringcentral-send-tollfree-sms#10]
Hi, 

We were using High Volume SMS for a few months and the phone number the texts would be sent FROM was our main office phone number. Now the number has changed. How can we change the number back? 
![Wrong number](https://user-images.githubusercontent.com/82917108/115479969-6862c280-a1fe-11eb-9633-e0ac282c0fa9.png)

thanks

Lauren

**Comment by PacoVu** [comment]
This is a non-programming feedback. Please use the feedback form in the app to contact RC Labs.
