### ISSUE TITLE
High Volume SMS fails to send with no failed reason

### ISSUE THREAD

**Issue by montemcdx** [PacoVu/ringcentral-send-tollfree-sms#11]
I tried to send a test messages to a set of 6 phone numbers and they all failed with no reason. How do I troubleshoot the issue?

![Screenshot 2021-05-05 125549](https://user-images.githubusercontent.com/61329030/117206796-84469680-adb0-11eb-8ccc-23ebc5efa9be.png)

**Comment by PacoVu** [comment]
This is a non-programming feedback. Please use the feedback form from the app to contact RC Labs.
