### ISSUE TITLE
Question on using your tool

### ISSUE THREAD

**Issue by mattsmithlp560** [PacoVu/ringcentral-send-tollfree-sms#2]
Hi Paco,

This seems like it's going to be the perfect tool for me! By any chance could you do a readme for instructions on how to utilize your tool? I thought this may have been a developer extension tool in chrome but it wasn't letting me load the unpacked folder. 

Greatly appreciate your work here!

Matt Smith

**Comment by PacoVu** [comment]
Hi Matt,

There are instructions how to use the app to send SMS on the "help" page.

**Comment by PacoVu** [comment]
> Hi Paco,
> 
> This seems like it's going to be the perfect tool for me! By any chance could you do a readme for instructions on how to utilize your tool? I thought this may have been a developer extension tool in chrome but it wasn't letting me load the unpacked folder.
> 
> Greatly appreciate your work here!
> 
> Matt Smith
