### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by tlsonya** [PacoVu/ringcentral-send-tollfree-sms#22]
Unable to log into Ring Central High Volume SMS. It  keep sending verification codes that does not work. I use the same password, which has not changed. 
[Ring Central Issue 07.15.21.pdf](https://github.com/PacoVu/ringcentral-send-tollfree-sms/files/6825072/Ring.Central.Issue.07.15.21.pdf)

**Comment by PacoVu** [comment]
Unfortunately, this issue is not related to this app. It's a general account access security and you should contact your IT admin or your RingCentral account manager.
