### ISSUE TITLE
Won't send high volume texts

### ISSUE THREAD

**Issue by cesarlg27** [PacoVu/ringcentral-send-tollfree-sms#6]
I'm testing the service but it won't let me send the messages. 

Error message says: undefined

![image](https://user-images.githubusercontent.com/76451020/102814390-2cbf0580-4390-11eb-9f6d-205a1dabb0f9.png)

**Comment by cesarlg27** [comment]
I gave it a campaign name and still won't do it

**Comment by PacoVu** [comment]
This is not programming questions so please use the feedback form instead. Not sure what happened but you can try again with the latest release.
