### ISSUE TITLE
Refresh tokken is missing

### ISSUE THREAD

**Issue by butt21** [PacoVu/ringcentral-send-tollfree-sms#8]
Why I'm receiving this pop up that "refresh token is missing" while sending [SMS] from Ring central high volume SMS application..

![Screenshot (254)](https://user-images.githubusercontent.com/79566460/108964674-97950180-769d-11eb-8915-09a169fadfb3.png)

**Comment by PacoVu** [comment]
This issue is fixed in the latest release
