### ISSUE TITLE
Toll-Free SMS Number not on the list

### ISSUE THREAD

**Issue by Christiiiiine** [PacoVu/ringcentral-send-tollfree-sms#9]
I requested this TF number (855) 554-6269 to be SMS enabled. I got to login on the app since i received an email that its already provisioned but i couldn't see it as an option when i'm about to send a message. 
![TF SMS](https://user-images.githubusercontent.com/82232465/114218723-cb6b7400-9937-11eb-8221-b9a6c56f3b46.PNG)

**Comment by PacoVu** [comment]
This is a non-programming feedback. Please use the feedback form in the app to contact RC Labs.
